Repository borglab/gtsam, pull requests merged in 2020-11, with the labels that each got.

#579 Consistent interface for pixel center
  gtsam/geometry/Cal3Bundler.h
  gtsam/gtsam.i
  gtsam/nonlinear/tests/testAdaptAutoDiff.cpp
  gtsam/slam/dataset.cpp
Labels: bugfix, easy-fix, quick-review

#583 Minor typo fixes
  gtsam/geometry/Rot3.h
  wrap/cmake/PybindWrap.cmake
Labels: docs, easy-fix, quick-review

#584 Fix python discovery for MATLAB wrapper
  cmake/HandlePython.cmake
Labels: cmake, matlab, quick-review

#593 Ubuntu+GCC9 CI stage
  .github/workflows/build-python.yml
Labels: ci, easy-fix, quick-review

#587 Github Actions Environment Files
  .github/workflows/build-linux.yml
  .github/workflows/build-macos.yml
  .github/workflows/build-python.yml
  .github/workflows/build-special.yml
  .github/workflows/build-windows.yml
Labels: ci, easy-fix, high-priority, quick-review

#597 Cayley Rot3 fixes
  .github/scripts/unix.sh
  .github/workflows/build-special.yml
  cmake/HandleGeneralOptions.cmake
  gtsam/geometry/Rot3M.cpp
  gtsam/geometry/tests/testPose3.cpp
  gtsam_unstable/geometry/tests/testSimilarity3.cpp
Labels: bugfix

#601 New print assertions
  gtsam/base/TestableAssertions.h
  gtsam/geometry/tests/testCal3_S2.cpp
  gtsam/geometry/tests/testPose3.cpp
  gtsam/nonlinear/tests/testFunctorizedFactor.cpp
  gtsam/nonlinear/tests/testValues.cpp
Labels: enhancement, feature

#603 Use KeyVector for proper wrapping with TBB
  gtsam/sfm/MFAS.cpp
  gtsam/sfm/MFAS.h
  gtsam/sfm/tests/testMFAS.cpp
Labels: bugfix, matlab, quick-review

#586 User-provided hook within the internal loop of non-linear optimizers
  gtsam/nonlinear/NonlinearConjugateGradientOptimizer.h
  gtsam/nonlinear/NonlinearOptimizer.cpp
  gtsam/nonlinear/NonlinearOptimizer.h
  gtsam/nonlinear/NonlinearOptimizerParams.h
  tests/testNonlinearOptimizer.cpp
Labels: enhancement, feature

#580 Flag for relative error
  gtsam/base/Matrix.h
  gtsam/base/Vector.cpp
  gtsam/base/Vector.h
  gtsam/base/tests/testMatrix.cpp
  gtsam/geometry/tests/testRot3.cpp
Labels: bugfix, high-priority, quick-review

#607 Enforce constant term in QP to be default 0
  gtsam_unstable/linear/QPSParser.cpp
Labels: bugfix, easy-fix, high-priority, quick-review

#602 Publish GTSAM artifacts
  .github/workflows/build-linux.yml
  .github/workflows/build-macos.yml
  .github/workflows/build-windows.yml
Labels: ci

#554 Check for MEX Compiler
  cmake/GtsamMatlabWrap.cmake
  cmake/HandleGeneralOptions.cmake
Labels: cmake, matlab

#622 Deprecate SimpleCamera properly
  gtsam/geometry/SimpleCamera.cpp
  gtsam/geometry/SimpleCamera.h
  gtsam/geometry/tests/testSimpleCamera.cpp
  gtsam/gtsam.i
  gtsam_unstable/slam/serialization.cpp
  python/gtsam/tests/test_SimpleCamera.py
  tests/testSerializationSLAM.cpp
Labels: cleanup, easy-fix

#616 Miscellaneous fixes
  examples/ImuFactorsExample.cpp
  gtsam/CMakeLists.txt
  python/gtsam/utils/plot.py
Labels: bugfix, quick-review

#608 Mark Values::at return type as const
  gtsam/nonlinear/Values-inl.h
  gtsam/nonlinear/Values.h
Labels: bugfix, quick-review
