Repository borglab/gtsam, pull requests merged in 2020-05, with the labels that each got.

#209 TBB deprecation fix (partial)
  examples/SolverComparer.cpp
  examples/TimeTBB.cpp
  gtsam/base/ThreadsafeException.h
  gtsam/base/debug.cpp
  gtsam/base/treeTraversal/parallelTraversalTasks.h
  gtsam/base/types.h
  gtsam/geometry/Unit3.cpp
  gtsam/geometry/Unit3.h
Labels: enhancement

#276 Better matrix printing
  gtsam/base/Matrix.cpp
  gtsam/geometry/Pose3.h
  gtsam/geometry/tests/testPose3.cpp
Labels: enhancement

#293 Plotting for new python wrapper
  wrap/python/gtsam_py/examples/SFMExample.py
  wrap/python/gtsam_py/examples/SFMdata.py
  wrap/python/gtsam_py/utils/plot.py
Labels: enhancement

#288 Representation for lines in 3D - Line3
  doc/math.lyx
  doc/math.pdf
  gtsam/geometry/Line3.cpp
  gtsam/geometry/Line3.h
  gtsam/geometry/tests/testLine3.cpp
  gtsam/slam/expressions.h
Labels: feature

#255 Python plotting upgrades
  cython/gtsam/examples/SFMExample.py
  cython/gtsam/examples/SFMdata.py
  cython/gtsam/utils/plot.py
  matlab/+gtsam/covarianceEllipse3D.m
Labels: enhancement

#183 Enable and fix unit tests in different archs
  debian/rules
  gtsam/geometry/tests/testOrientedPlane3.cpp
  gtsam/geometry/tests/testPose3.cpp
  gtsam/geometry/tests/testUnit3.cpp
  gtsam/slam/tests/testSmartProjectionPoseFactor.cpp
Labels: bugfix, enhancement

#313 Demangle the type when printing
  gtsam/CMakeLists.txt
  gtsam/base/GenericValue.h
  gtsam/base/types.cpp
  gtsam/base/types.h
  gtsam/nonlinear/Values.cpp
  gtsam/nonlinear/internal/ExpressionNode.h
  gtsam/nonlinear/tests/testValues.cpp
Labels: enhancement

#323 Optional jacobian computation in PreintegrationBase predict function
  gtsam/navigation/PreintegrationBase.cpp
Labels: enhancement
