Repository borglab/gtsam, pull requests merged in 2020-08, with the labels that each got.

#419 Values Print Formatting
  gtsam/base/GenericValue.h
  gtsam/geometry/tests/testPose3.cpp
  gtsam/navigation/tests/testNavState.cpp
  gtsam/nonlinear/Values.cpp
  gtsam/nonlinear/tests/testValues.cpp
Labels: enhancement

#422 Dellaert/issue420
  .travis.python.sh
  .travis.sh
  .travis.yml
  CMakeLists.txt
  README.md
  gtsam/base/DSFVector.h
  gtsam/base/Manifold.h
  gtsam/base/Matrix.h
  gtsam/base/Vector.h
  gtsam/config.h.in
  gtsam/geometry/EssentialMatrix.h
  gtsam/geometry/Point2.cpp
  gtsam/geometry/Point2.h
  gtsam/geometry/Point3.cpp
  gtsam/geometry/Point3.h
  gtsam/geometry/Pose2.h
  gtsam/geometry/Pose3.cpp
  gtsam/geometry/Pose3.h
  gtsam/geometry/Rot3.h
  gtsam/geometry/triangulation.h
  gtsam/inference/BayesTree.h
  gtsam/inference/ISAM.h
  gtsam/linear/GaussianConditional.h
  gtsam/linear/HessianFactor.h
  gtsam/linear/LossFunctions.h
  gtsam/linear/NoiseModel.cpp
  gtsam/linear/NoiseModel.h
  gtsam/linear/Sampler.cpp
  gtsam/linear/Sampler.h
  gtsam/linear/SubgraphSolver.cpp
  gtsam/linear/SubgraphSolver.h
  gtsam/navigation/AHRSFactor.h
  gtsam/navigation/CombinedImuFactor.cpp
  gtsam/navigation/CombinedImuFactor.h
  gtsam/navigation/ImuFactor.cpp
  gtsam/navigation/ImuFactor.h
  gtsam/navigation/PreintegrationBase.cpp
  gtsam/navigation/PreintegrationBase.h
  gtsam/navigation/ScenarioRunner.h
  gtsam/navigation/tests/testNavState.cpp
  gtsam/navigation/tests/testPoseVelocityBias.cpp
  gtsam/nonlinear/LinearContainerFactor.h
  gtsam/nonlinear/NonlinearFactor.h
  gtsam/slam/SmartProjectionFactor.h
  gtsam/slam/dataset.h
  gtsam_unstable/nonlinear/BatchFixedLagSmoother.h
  tests/testManifold.cpp
Labels: bugfix, enhancement

#455 Fix warning in FrobeniusWormholeFactor
  gtsam/slam/FrobeniusFactor.cpp
Labels: enhancement

#468 Default string value for printing Imu factors
  gtsam/navigation/CombinedImuFactor.cpp
  gtsam/navigation/CombinedImuFactor.h
  gtsam/navigation/ImuFactor.cpp
  gtsam/navigation/ImuFactor.h
  gtsam/navigation/PreintegratedRotation.cpp
  gtsam/navigation/PreintegrationBase.cpp
  gtsam/navigation/PreintegrationBase.h
Labels: feature, quick-review

#470 Fix FrobeniusBetweenFactor declaration
  .travis.yml
  gtsam/slam/FrobeniusFactor.h
Labels: bugfix, high-priority, quick-review

#462 Consistent width printing of CMake flags
  CMakeLists.txt
  cmake/GtsamPrinting.cmake
Labels: cmake, feature

#457 Update plot_pose2 to stop trying to set zlabel on axes with no z-axis
  cython/gtsam/utils/plot.py
Labels: bugfix

#471 Feature/dataset refactor
  .travis.yml
  examples/Data/example_with_vertices.g2o
  gtsam/nonlinear/Values.h
  gtsam/sam/BearingRangeFactor.h
  gtsam/sfm/BinaryMeasurement.h
  gtsam/slam/dataset.cpp
  gtsam/slam/dataset.h
  gtsam/slam/tests/testDataset.cpp
  tests/testNonlinearISAM.cpp
  timing/timeFrobeniusFactor.cpp
Labels: cleanup, refactor

#472 Minimal PR to add GitHub Actions CI to develop
  .github/scripts/python.sh
  .github/scripts/unix.sh
  .github/workflows/build-linux.yml
  .github/workflows/build-macos.yml
  .github/workflows/build-python.yml
  .github/workflows/build-windows.yml
  .github/workflows/trigger-python.yml
  .travis.python.sh
  .travis.yml
  appveyor.yml
  cython/gtsam/utils/visual_data_generator.py
  gtsam/base/GenericValue.h
  gtsam/slam/BetweenFactor.h
Labels: ci, enhancement

#473 Feature/shonan averaging
  .gitignore
  cython/gtsam/tests/test_FrobeniusFactor.py
  examples/Data/Klaus3.g2o
  gtsam.h
  gtsam/geometry/Rot2.cpp
  gtsam/geometry/Rot2.h
  gtsam/geometry/SOn-inl.h
  gtsam/geometry/SOn.cpp
  gtsam/geometry/SOn.h
  gtsam/geometry/tests/testSOn.cpp
  gtsam/nonlinear/NonlinearOptimizer.cpp
  gtsam/sfm/ShonanAveraging.cpp
  gtsam/sfm/ShonanAveraging.h
  gtsam/sfm/ShonanFactor.cpp
  gtsam/sfm/ShonanFactor.h
  gtsam/sfm/ShonanGaugeFactor.h
  gtsam/sfm/tests/testShonanAveraging.cpp
  gtsam/sfm/tests/testShonanFactor.cpp
  gtsam/sfm/tests/testShonanGaugeFactor.cpp
  gtsam/slam/FrobeniusFactor.cpp
  gtsam/slam/FrobeniusFactor.h
  gtsam/slam/KarcherMeanFactor-inl.h
  gtsam/slam/KarcherMeanFactor.h
  gtsam/slam/tests/testFrobeniusFactor.cpp
  gtsam_unstable/gtsam_unstable.h
  gtsam_unstable/timing/process_shonan_timing_results.py
  gtsam_unstable/timing/timeShonanAveraging.cpp
  timing/timeShonanFactor.cpp
Labels: feature, high-priority

#476 Improve Github Actions
  .github/scripts/unix.sh
  README.md
Labels: ci, wip

#501 Example Datasets with Python Package
  gtsam/gtsam.i
  python/CMakeLists.txt
  python/gtsam/__init__.py
  python/gtsam/utils/__init__.py
  python/setup.py.in
Labels: python
