Repository borglab/gtsam, pull requests merged in 2020-07, with the labels that each got.

#371 Capture stdout in python test
  cython/gtsam/tests/test_logging_optimizer.py
  cython/gtsam/utils/logging_optimizer.py
Labels: feature, python

#373 Fix memory leak in Expressions
  gtsam/nonlinear/internal/ExecutionTrace.h
  gtsam/nonlinear/tests/testExecutionTrace.cpp
Labels: bugfix

#360 Frobenius error factor
  cython/gtsam/tests/test_FrobeniusFactor.py
  gtsam.h
  gtsam/slam/FrobeniusFactor.cpp
  gtsam/slam/FrobeniusFactor.h
  gtsam/slam/tests/testFrobeniusFactor.cpp
  timing/timeFrobeniusFactor.cpp
Labels: feature

#384 Unnecessary include statement
  gtsam/geometry/SOn.h
Labels: quick-review

#334 Fix Unit3 copy assign
  gtsam/geometry/Unit3.h
  gtsam/geometry/tests/testUnit3.cpp
Labels: bugfix

#393 CMake print Matlab info
  CMakeLists.txt
Labels: cmake, feature

#379 Test body_P_sensor in SmartFactor
  gtsam/geometry/PinholePose.h
  gtsam/slam/SmartFactorBase.h
  gtsam/slam/tests/testSmartFactorBase.cpp
Labels: bugfix

#391 Generic Eigen::Matrix serialization for boost
  gtsam/base/Matrix.h
  gtsam/navigation/ImuFactor.h
  gtsam/navigation/ManifoldPreintegration.h
  gtsam/navigation/PreintegratedRotation.h
  gtsam/navigation/PreintegrationParams.h
  gtsam/navigation/TangentPreintegration.h
Labels: feature

#395 IMUKittiExampleGPS fixes
  examples/IMUKittiExampleGPS.cpp
  examples/SFMExample.cpp
Labels: feature

#386 CombinedImuFactor Serialization Fix
  gtsam/navigation/CombinedImuFactor.cpp
  gtsam/navigation/CombinedImuFactor.h
  gtsam/navigation/ImuFactor.h
  gtsam/navigation/ManifoldPreintegration.h
  gtsam/navigation/PreintegratedRotation.cpp
  gtsam/navigation/PreintegrationBase.h
  gtsam/navigation/PreintegrationParams.cpp
  gtsam/navigation/PreintegrationParams.h
  gtsam/navigation/TangentPreintegration.h
  gtsam/navigation/tests/testImuFactorSerialization.cpp
Labels: bugfix

#392 Suppress 3rd Party Warnings in Release mode
  gtsam/CMakeLists.txt
Labels: cmake, feature, quick-review

#397 CMake policy for AppleClang compiler identification
  cmake/GtsamBuildTypes.cmake
Labels: bugfix, quick-review

#394 Wrap the Conjugate Gradient Solver Interface in Cython
  cython/gtsam/tests/test_NonlinearOptimizer.py
  gtsam.h
  gtsam/linear/PCGSolver.cpp
  gtsam/linear/PCGSolver.h
Labels: quick-review

#401 CombinedImuParams Equality Comparison
  gtsam/navigation/CombinedImuFactor.cpp
  gtsam/navigation/CombinedImuFactor.h
Labels: bugfix, quick-review

#329 Functorized Factor
  gtsam/nonlinear/FunctorizedFactor.h
  gtsam/nonlinear/tests/testFunctorizedFactor.cpp
Labels: design, enhancement, feature

#404 Fix serialization warning for boost::optional<Vector3>
  gtsam/navigation/PreintegratedRotation.h
Labels: bugfix, quick-review

#241 RFC: Adding a number of docker images
  docker/README.md
  docker/ubuntu-boost-tbb-eigen3/Dockerfile
  docker/ubuntu-boost-tbb/Dockerfile
  docker/ubuntu-boost-tbb/build.sh
  docker/ubuntu-gtsam-python-vnc/Dockerfile
  docker/ubuntu-gtsam-python-vnc/bootstrap.sh
  docker/ubuntu-gtsam-python-vnc/build.sh
  docker/ubuntu-gtsam-python-vnc/vnc.sh
  docker/ubuntu-gtsam-python/Dockerfile
  docker/ubuntu-gtsam-python/build.sh
  docker/ubuntu-gtsam/Dockerfile
  docker/ubuntu-gtsam/build.sh
Labels: enhancement, feature

#409 Correct indentation for Python version
  CMakeLists.txt
Labels: feature, quick-review

#277 Auto-install Python Package
  .travis.python.sh
  CMakeLists.txt
  cmake/GtsamCythonWrap.cmake
  cython/CMakeLists.txt
  cython/README.md
  cython/gtsam_eigency/CMakeLists.txt
  cython/setup.py.in
Labels: cmake, enhancement, python

#418 Added more comments for clearer understanding
  gtsam/navigation/TangentPreintegration.cpp
Labels: docs

#425 remove unused base variable
  gtsam/nonlinear/FunctorizedFactor.h
Labels: enhancement

#428 Plotting updates
  cython/gtsam/utils/plot.py
Labels: feature

#429 Travis timeout fixes
  .travis.yml
Labels: bugfix

#442 Add C++11 brace initializer_list to Values
  gtsam/base/GenericValue.h
  gtsam/nonlinear/Values.cpp
  gtsam/nonlinear/Values.h
  gtsam/nonlinear/tests/testValues.cpp
Labels: feature

#358 Consistent Rot3 printing
  gtsam/base/Matrix.cpp
  gtsam/base/Matrix.h
  gtsam/geometry/Pose3.cpp
  gtsam/geometry/Rot3.cpp
  gtsam/geometry/Rot3.h
  gtsam/geometry/tests/testPose3.cpp
  gtsam/geometry/tests/testRot3.cpp
  gtsam/linear/JacobianFactor.cpp
  gtsam/navigation/NavState.cpp
  gtsam/navigation/tests/testNavState.cpp
  gtsam/nonlinear/tests/testFunctorizedFactor.cpp
Labels: design, enhancement, feature

#440 Minor updates to the pybind wrapper
  python/CMakeLists.txt
  python/gtsam_py/python/__init__.py
  python/setup.py.in
Labels: enhancement

#445 remove empty smart folder
  gtsam/CMakeLists.txt
  gtsam/smart/CMakeLists.txt
  gtsam/smart/tests/CMakeLists.txt
Labels: enhancement

#451 Wrap preintegrated function
  gtsam.h
Labels: python, quick-review
