Repository borglab/gtsam, pull requests merged in 2020-06, with the labels that each got.

#338 Add addPrior to wrapper
  cython/gtsam/tests/test_PriorFactor.py
  gtsam.h
Labels: feature, matlab, python

#347 Wrapper Updates for Global Functions
  cython/gtsam/examples/ImuFactorExample.py
  cython/gtsam/examples/ImuFactorExample2.py
  cython/gtsam/examples/PlanarSLAMExample.py
  cython/gtsam/examples/Pose2SLAMExample_g2o.py
  cython/gtsam/examples/Pose3SLAMExample_g2o.py
  cython/gtsam/examples/README.md
  cython/gtsam/examples/SFMExample.py
  cython/gtsam/examples/SimpleRotation.py
  cython/gtsam/examples/VisualISAM2Example.py
  cython/gtsam/examples/VisualISAMExample.py
  cython/gtsam/tests/test_GaussianFactorGraph.py
  cython/gtsam/tests/test_dsf_map.py
  cython/gtsam/utils/plot.py
  gtsam.h
  wrap/GlobalFunction.h
Labels: enhancement, feature

#353 Renamed testScenarios.cpp to testScenarioRunner.cpp
  gtsam/navigation/tests/testScenarioRunner.cpp
Labels: bugfix

#366 Set minimum supported numpy version
  .travis.yml
  cython/requirements.txt
Labels: ci, quick-review

#364 Export Cython Install Path
  gtsam_extra.cmake.in
Labels: cmake, quick-review

#370 Minor Updates
  gtsam.h
  gtsam/3rdparty/CMakeLists.txt
Labels: feature, quick-review

#367 Translation averaging
  gtsam/sfm/TranslationFactor.h
  gtsam/sfm/TranslationRecovery.cpp
  gtsam/sfm/TranslationRecovery.h
  gtsam/sfm/tests/testTranslationFactor.cpp
  tests/testTranslationRecovery.cpp
Labels: feature
