Repository borglab/gtsam, pull requests merged in 2020-09, with the labels that each got.

#503 General check for null pointer in saveGraph
  gtsam/nonlinear/NonlinearFactorGraph.cpp
Labels: bugfix

#502 Update NavState Printing
  gtsam/navigation/NavState.cpp
  gtsam/navigation/tests/testNavState.cpp
Labels: feature

#506 New readBal function
  gtsam/slam/dataset.cpp
  gtsam/slam/dataset.h
Labels: feature, quick-review

#509 Update minimum Boost version required
  CMakeLists.txt
  INSTALL.md
  README.md
Labels: feature

#510 Wrapper fixes
  gtsam/gtsam.i
Labels: python

#527 TranslationRecovery Fixes
  gtsam/sfm/TranslationRecovery.cpp
  gtsam/sfm/TranslationRecovery.h
  python/gtsam/tests/test_TranslationRecovery.py
Labels: enhancement, quick-review

#529 Minor typo fix
  gtsam/base/OptionalJacobian.h
Labels: easy-fix, quick-review

#387 Minimum Feedback Arc Set (MFAS) for 1dsfm
  gtsam/sfm/MFAS.cpp
  gtsam/sfm/MFAS.h
  gtsam/sfm/tests/testMFAS.cpp
Labels: feature

#531 Update cmake printing
  CMakeLists.txt
  cmake/GtsamPrinting.cmake
Labels: cmake

#526 Automatically find Python3 version
  CMakeLists.txt
  cmake/FindNumPy.cmake
  cmake/GtsamMatlabWrap.cmake
Labels: python

#538 Remove logmap function from LieVector and LieMatrix
  gtsam/gtsam.i
Labels: bugfix, easy-fix, high-priority, quick-review

#540 ImuFactorExample minor fixes
  python/gtsam/examples/ImuFactorExample.py
Labels: python, quick-review

#507 correct coefficients of approximated SE3 Q_r
  gtsam/geometry/Pose3.cpp
  gtsam/geometry/Pose3.h
  gtsam/geometry/tests/testPose3.cpp
Labels: bugfix

#541 Wrap update
  wrap/matlab_wrapper.py
Labels: matlab

#536 Add numericalDerivative Dimension Template Parameter
  gtsam/base/numericalDerivative.h
  gtsam/base/tests/testNumericalDerivative.cpp
Labels: bugfix, enhancement, quick-review

#464 Update Simitary3 with Align feature
  gtsam/geometry/Point3.cpp
  gtsam/geometry/Point3.h
  gtsam/geometry/Pose3.h
  gtsam/geometry/tests/testPoint3.cpp
  gtsam_unstable/geometry/Similarity3.cpp
  gtsam_unstable/geometry/Similarity3.h
  gtsam_unstable/geometry/tests/testSimilarity3.cpp
Labels: feature

#518 ISAM2 Evaluate Nonlinear Error
  gtsam/gtsam.i
  gtsam/nonlinear/ISAM2Result.h
Labels: feature, python

#542 Point3 mean to throw an exception when input size=0 .
  gtsam/geometry/Point3.cpp
  gtsam/geometry/Point3.h
Labels: enhancement

#539 Add calibrate with jacobians for Cal3Bundler
  gtsam/geometry/Cal3Bundler.cpp
  gtsam/geometry/Cal3Bundler.h
  gtsam/geometry/tests/testCal3Bundler.cpp
  gtsam/geometry/tests/testPinholeCamera.cpp
  gtsam/gtsam.i
Labels: bugfix, help wanted

#545 Minor fixes
  gtsam/geometry/Cal3Bundler.cpp
  gtsam/gtsam.i
Labels: enhancement
