Repository borglab/gtsam, pull requests merged in 2020-12, with the labels that each got.

#623 Jacobians for Camera models
  gtsam/geometry/Cal3.h
  gtsam/geometry/Cal3Bundler.cpp
  gtsam/geometry/Cal3Bundler.h
  gtsam/geometry/Cal3DS2.h
  gtsam/geometry/Cal3DS2_Base.cpp
  gtsam/geometry/Cal3DS2_Base.h
  gtsam/geometry/Cal3Fisheye.cpp
  gtsam/geometry/Cal3Fisheye.h
  gtsam/geometry/Cal3Unified.cpp
  gtsam/geometry/Cal3Unified.h
  gtsam/geometry/SimpleCamera.h
  gtsam/geometry/tests/testCal3DFisheye.cpp
  gtsam/geometry/tests/testCal3DS2.cpp
  gtsam/geometry/tests/testCal3Unified.cpp
  gtsam/gtsam.i
  gtsam_unstable/slam/serialization.cpp
  tests/testSerializationSLAM.cpp
Labels: bugfix, high-priority

#624 IMU Parameters Documentation
  gtsam/navigation/ImuBias.h
  gtsam/navigation/PreintegratedRotation.h
  gtsam/navigation/PreintegrationParams.h
Labels: docs, quick-review

#626 Cal3 Base Class
  gtsam/geometry/Cal3.cpp
  gtsam/geometry/Cal3.h
  gtsam/geometry/Cal3Bundler.cpp
  gtsam/geometry/Cal3Bundler.h
  gtsam/geometry/Cal3DS2.cpp
  gtsam/geometry/Cal3DS2.h
  gtsam/geometry/Cal3DS2_Base.cpp
  gtsam/geometry/Cal3DS2_Base.h
  gtsam/geometry/Cal3Fisheye.cpp
  gtsam/geometry/Cal3Fisheye.h
  gtsam/geometry/Cal3Unified.cpp
  gtsam/geometry/Cal3Unified.h
  gtsam/geometry/Cal3_S2.cpp
  gtsam/geometry/Cal3_S2.h
  gtsam/geometry/Cal3_S2Stereo.cpp
  gtsam/geometry/Cal3_S2Stereo.h
  gtsam/geometry/tests/testCal3Bundler.cpp
  gtsam/geometry/tests/testCal3DFisheye.cpp
  gtsam/geometry/tests/testCal3DS2.cpp
  gtsam/geometry/tests/testCal3Unified.cpp
  gtsam/geometry/tests/testCal3_S2.cpp
  gtsam/geometry/tests/testCal3_S2Stereo.cpp
  gtsam/gtsam.i
Labels: cleanup, design, enhancement, refactor

#630 Cal3_S2Stereo Calibrate and Uncalibrate
  gtsam/geometry/Cal3_S2.cpp
  gtsam/geometry/Cal3_S2Stereo.cpp
  gtsam/geometry/Cal3_S2Stereo.h
  gtsam/geometry/tests/testCal3_S2Stereo.cpp
Labels: feature

#615 vector of cameras and triangulation function wrapped
  gtsam/geometry/triangulation.h
  gtsam/gtsam.i
  python/CMakeLists.txt
  python/gtsam/preamble.h
  python/gtsam/specializations.h
  python/gtsam/tests/test_Triangulation.py
Labels: python

#632 NonlinearFactorGraph saveGraph
  gtsam/gtsam.i
  gtsam/nonlinear/NonlinearFactorGraph.cpp
  gtsam/nonlinear/NonlinearFactorGraph.h
Labels: feature, python, quick-review

#635 Explicitly initialize Point3
  gtsam/slam/tests/testInitializePose3.cpp
Labels: easy-fix, quick-review

#642 Wrap Symbol class and methods
  gtsam/gtsam.i
  gtsam/inference/Symbol.h
Labels: matlab, python, quick-review

#643 Minor formatting
  cmake/GtsamTesting.cmake
Labels: quick-review, refactor

#644 Wrapping prior factor and general sfm factor or Cal3Bundler
  gtsam/gtsam.i
Labels: easy-fix, enhancement, python, quick-review

#645 Python support for CMake version < 3.12
  cmake/HandlePython.cmake
Labels: cmake, python

#647 Pose3 interpolateRt method
  gtsam/geometry/Pose3.h
  gtsam/geometry/tests/testPose3.cpp
Labels: bugfix, high-priority
