Repository borglab/gtsam, pull requests merged in 2021-07, with the labels that each got.

#814 Miscellaneous fixes
  gtsam/geometry/Pose3.h
  gtsam/gtsam.i
Labels: easy-fix, quick-review

#813 Tests for BetweenFactor
  gtsam/slam/tests/testBetweenFactor.cpp
Labels: easy-fix, feature, quick-review

#766 refactor Expression tests and add comments
  gtsam/nonlinear/tests/testExpression.cpp
  tests/testExpressionFactor.cpp
Labels: quick-review, refactor

#830 Wrap Update
  wrap/gtwrap/interface_parser/classes.py
  wrap/gtwrap/interface_parser/function.py
  wrap/gtwrap/interface_parser/type.py
  wrap/gtwrap/matlab_wrapper/mixins.py
  wrap/gtwrap/matlab_wrapper/wrapper.py
  wrap/gtwrap/template_instantiator.py
  wrap/requirements.txt
  wrap/tests/test_matlab_wrapper.py
Labels: wrapper
