Repository borglab/gtsam, pull requests merged in 2021-11, with the labels that each got.

#862 Smart Factors for arbitrary cameras
  gtsam/slam/JacobianFactorSVD.h
  gtsam/slam/ProjectionFactor.h
  gtsam/slam/ReadMe.md
  gtsam/slam/RegularImplicitSchurFactor.h
  gtsam/slam/SmartFactorBase.h
  gtsam/slam/SmartProjectionFactor.h
  gtsam/slam/SmartProjectionRigFactor.h
  gtsam/slam/tests/smartFactorScenarios.h
  gtsam/slam/tests/testSmartProjectionRigFactor.cpp
  gtsam_unstable/slam/ReadMe.md
  gtsam_unstable/slam/SmartProjectionPoseFactorRollingShutter.h
  gtsam_unstable/slam/SmartStereoProjectionFactor.h
  gtsam_unstable/slam/SmartStereoProjectionFactorPP.h
  gtsam_unstable/slam/tests/testSmartProjectionPoseFactorRollingShutter.cpp
Labels: feature

#915 Fix warnings raised by GCC -Wpedactic
  gtsam/base/Lie.h
  gtsam/base/Manifold.h
  gtsam/base/Matrix.h
  gtsam/base/Testable.h
  gtsam/base/Vector.h
  gtsam/base/chartTesting.h
  gtsam/geometry/PinholePose.h
  gtsam/geometry/Pose2.cpp
  gtsam/geometry/Pose3.cpp
  gtsam/geometry/concepts.h
  gtsam/inference/ClusterTree.h
  gtsam/inference/EliminationTree.h
  gtsam/linear/tests/testSerializationLinear.cpp
  gtsam/navigation/CombinedImuFactor.cpp
  gtsam/navigation/CombinedImuFactor.h
  gtsam/navigation/tests/testAttitudeFactor.cpp
  gtsam/navigation/tests/testImuFactorSerialization.cpp
  gtsam/nonlinear/CustomFactor.h
  gtsam/nonlinear/NonlinearConjugateGradientOptimizer.h
  gtsam/nonlinear/NonlinearEquality.h
  gtsam/nonlinear/tests/testSerializationNonlinear.cpp
  gtsam/slam/GeneralSFMFactor.h
  gtsam/slam/tests/testSmartFactorBase.cpp
  gtsam/slam/tests/testSmartProjectionFactor.cpp
  gtsam/slam/tests/testSmartProjectionPoseFactor.cpp
  gtsam_unstable/linear/tests/testQPSolver.cpp
  gtsam_unstable/slam/BetweenFactorEM.h
  tests/testExpressionFactor.cpp
  tests/testSerializationSLAM.cpp
  tests/testSubgraphPreconditioner.cpp
Labels: quick-review, low-priority

#920 Fix minor stuff
  gtsam/inference/EliminateableFactorGraph-inst.h
  gtsam/nonlinear/GncOptimizer.h
  gtsam/nonlinear/factorTesting.h
  gtsam/nonlinear/nonlinear.i
  python/gtsam/examples/SFMExample_bal.py
Labels: cleanup

#921 CMake fix for Python Tests
  python/CMakeLists.txt
Labels: python, cmake

#922 Add Jacobian of second argument to `adjoint` and `adjointTranpsose`
  gtsam/geometry/Pose3.cpp
  gtsam/geometry/Pose3.h
  gtsam/geometry/geometry.i
  gtsam/geometry/tests/testPose3.cpp
  python/gtsam/tests/test_Pose3.py
Labels: quick-review

#925 Proper Deprecation of Eliminate Methods
  gtsam/inference/EliminateableFactorGraph-inst.h
  gtsam/inference/EliminateableFactorGraph.h
  gtsam/linear/GaussianFactorGraph.cpp
  gtsam/linear/GaussianFactorGraph.h
  gtsam/nonlinear/Marginals.cpp
  gtsam/nonlinear/Marginals.h
  gtsam/nonlinear/NonlinearFactorGraph.h
  gtsam/nonlinear/NonlinearOptimizer.cpp
Labels: quick-review, refactor

#930 Formatting with Google style
  gtsam_unstable/discrete/AllDiff.cpp
  gtsam_unstable/discrete/AllDiff.h
  gtsam_unstable/discrete/BinaryAllDiff.h
  gtsam_unstable/discrete/CSP.cpp
  gtsam_unstable/discrete/CSP.h
  gtsam_unstable/discrete/Constraint.h
  gtsam_unstable/discrete/Domain.cpp
  gtsam_unstable/discrete/Domain.h
  gtsam_unstable/discrete/Scheduler.cpp
  gtsam_unstable/discrete/Scheduler.h
  gtsam_unstable/discrete/SingleValue.cpp
  gtsam_unstable/discrete/SingleValue.h
  gtsam_unstable/discrete/tests/testCSP.cpp
  gtsam_unstable/discrete/tests/testLoopyBelief.cpp
  gtsam_unstable/discrete/tests/testScheduler.cpp
  gtsam_unstable/discrete/tests/testSudoku.cpp
Labels: quick-review, cleanup

#932 Wrap KeyVector methods
  gtsam/linear/linear.i
Labels: quick-review, wrapper

#942 Enable pickling
  gtsam/linear/NoiseModel.h
  gtsam/linear/linear.i
  gtsam/navigation/navigation.i
Labels: high-priority

#943 Fix deprecations
  gtsam/base/tests/testVector.cpp
  gtsam/linear/Errors.cpp
  gtsam/linear/Errors.h
  gtsam/linear/SubgraphPreconditioner.cpp
  gtsam/linear/iterative-inl.h
  gtsam/linear/tests/testErrors.cpp
  gtsam/nonlinear/DoglegOptimizerImpl.cpp
Labels: refactor

#944 Eigen Serialization Fix
  gtsam/base/serialization.h
Labels: bugfix, refactor

#941 Wrap additional ISAM2 methods
  gtsam/linear/NoiseModel.h
  gtsam/linear/linear.i
  gtsam/navigation/navigation.i
  gtsam/nonlinear/LinearContainerFactor.h
  gtsam/nonlinear/nonlinear.i
Labels: quick-review, high-priority

#188 Make mEstimator variable names consistent with math
  gtsam/linear/NoiseModel.h
  gtsam/linear/tests/testNoiseModel.cpp
  gtsam/nonlinear/NonlinearFactor.cpp
  tests/testNonlinearFactor.cpp
Labels: enhancement

#933 Modernize discrete factor graphs (a bit)
  examples/DiscreteBayesNetExample.cpp
  examples/DiscreteBayesNet_FG.cpp
  examples/HMMExample.cpp
  examples/UGM_chain.cpp
  examples/UGM_small.cpp
  gtsam/discrete/DiscreteBayesNet.cpp
  gtsam/discrete/DiscreteBayesNet.h
  gtsam/discrete/DiscreteConditional.cpp
  gtsam/discrete/DiscreteConditional.h
  gtsam/discrete/DiscreteFactor.h
  gtsam/discrete/DiscreteFactorGraph.cpp
  gtsam/discrete/DiscreteFactorGraph.h
  gtsam/discrete/tests/testDiscreteBayesNet.cpp
  gtsam/discrete/tests/testDiscreteFactorGraph.cpp
  gtsam_unstable/discrete/CSP.cpp
  gtsam_unstable/discrete/CSP.h
  gtsam_unstable/discrete/Scheduler.cpp
  gtsam_unstable/discrete/Scheduler.h
  gtsam_unstable/discrete/examples/schedulingExample.cpp
  gtsam_unstable/discrete/examples/schedulingQuals12.cpp
  gtsam_unstable/discrete/examples/schedulingQuals13.cpp
  gtsam_unstable/discrete/tests/testCSP.cpp
  gtsam_unstable/discrete/tests/testScheduler.cpp
  gtsam_unstable/discrete/tests/testSudoku.cpp
Labels: quick-review, cleanup
