Repository borglab/gtsam, pull requests merged in 2021-05, with the labels that each got.

#763 Update boost download link
  .github/scripts/boost.sh
Labels: ci, easy-fix, high-priority, quick-review

#761 Fix warnings
  gtsam/geometry/CalibratedCamera.h
  gtsam/geometry/tests/testRot3.cpp
  gtsam/inference/Factor.h
  gtsam/inference/FactorGraph.h
Labels: cleanup

#762 Interface file updates
  gtsam/gtsam.i
  python/gtsam/gtsam.tpl
Labels: quick-review

#696 smart factors with extrinsics calibration
  gtsam/geometry/CameraSet.h
  gtsam_unstable/slam/SmartStereoProjectionFactor.h
  gtsam_unstable/slam/SmartStereoProjectionFactorPP.cpp
  gtsam_unstable/slam/SmartStereoProjectionFactorPP.h
  gtsam_unstable/slam/tests/testSmartStereoProjectionFactorPP.cpp
Labels: enhancement

#777 Fix rekey of LinearContainerFactor
  gtsam/nonlinear/LinearContainerFactor.cpp
  gtsam/nonlinear/LinearContainerFactor.h
  gtsam/nonlinear/NonlinearFactor.h
  gtsam/nonlinear/tests/testLinearContainerFactor.cpp
Labels: bugfix
