Repository borglab/gtsam, pull requests merged in 2021-08, with the labels that each got.

#835 Add Windows export symbols for PinholeCamera
  gtsam/geometry/PinholeCamera.h
  gtsam/geometry/PinholePose.h
Labels: bugfix, easy-fix, quick-review

#839 CI Speedup
  .github/scripts/boost.sh
  .github/scripts/unix.sh
  .github/workflows/build-linux.yml
  .github/workflows/build-macos.yml
  .github/workflows/build-python.yml
  .github/workflows/build-special.yml
  .github/workflows/build-windows.yml
Labels: performance

#842 Add missing getter in ProjectionFactor
  gtsam/slam/ProjectionFactor.h
Labels: quick-review

#851 Fix utilities and add tests
  gtsam/geometry/tests/testUtilities.cpp
  gtsam/gtsam.i
  gtsam/nonlinear/utilities.h
  python/gtsam/tests/test_Utilities.py
Labels: bugfix

#850 Some Cleanup
  DEVELOP.md
  INSTALL.md
  README.md
  Using-GTSAM-EXPORT.md
  cmake/HandleBoost.cmake
  cmake/HandleCPack.cmake
  gtsam/base/base.i
  gtsam/nonlinear/NonlinearEquality.h
  gtsam/nonlinear/nonlinear.i
Labels: quick-review

#856 Wrap NonlinearEquality2
  gtsam/nonlinear/NonlinearEquality.h
  gtsam/nonlinear/nonlinear.i
  python/CMakeLists.txt
  python/gtsam/tests/test_Factors.py
Labels: python, quick-review, high-priority

#858 Add missing import of Pose3
  python/gtsam/utils/plot.py
Labels: quick-review

#827 Feature/rolling shutter smart factors
  gtsam/base/Lie.h
  gtsam/geometry/CameraSet.h
  gtsam/geometry/tests/testCameraSet.cpp
  gtsam/geometry/tests/testPose3.cpp
  gtsam/slam/SmartFactorBase.h
  gtsam/slam/SmartProjectionFactor.h
  gtsam/slam/tests/testSmartProjectionPoseFactor.cpp
  gtsam_unstable/slam/ProjectionFactorRollingShutter.cpp
  gtsam_unstable/slam/ProjectionFactorRollingShutter.h
  gtsam_unstable/slam/SmartProjectionPoseFactorRollingShutter.h
  gtsam_unstable/slam/SmartStereoProjectionFactorPP.h
  gtsam_unstable/slam/tests/testProjectionFactorRollingShutter.cpp
  gtsam_unstable/slam/tests/testSmartProjectionPoseFactorRollingShutter.cpp
Labels: feature

#863 Fix Python Tests Cmake
  .github/scripts/python.sh
  gtsam/basis/Fourier.h
  python/CMakeLists.txt
  python/gtsam/tests/test_basis.py
Labels: bugfix, python

#865 Docs and formatting
  gtsam/slam/JacobianFactorSVD.h
  gtsam/slam/ProjectionFactor.h
  gtsam/slam/ReadMe.md
  gtsam/slam/RegularImplicitSchurFactor.h
  gtsam/slam/SmartFactorBase.h
  gtsam/slam/SmartProjectionFactor.h
  gtsam/slam/SmartProjectionFactorP.h
  gtsam_unstable/slam/ReadMe.md
  gtsam_unstable/slam/SmartStereoProjectionFactor.h
  gtsam_unstable/slam/SmartStereoProjectionFactorPP.h
Labels: docs, cleanup
