Repository borglab/gtsam, pull requests merged in 2021-12, with the labels that each got.

#861 spherical camera
  gtsam/geometry/PinholeCamera.h
  gtsam/geometry/PinholePose.h
  gtsam/geometry/SphericalCamera.cpp
  gtsam/geometry/SphericalCamera.h
  gtsam/geometry/StereoCamera.h
  gtsam/geometry/tests/testSphericalCamera.cpp
  gtsam/geometry/tests/testTriangulation.cpp
  gtsam/geometry/triangulation.cpp
  gtsam/geometry/triangulation.h
  gtsam/slam/README.md
  gtsam/slam/SmartProjectionRigFactor.h
  gtsam/slam/TriangulationFactor.h
  gtsam/slam/tests/smartFactorScenarios.h
  gtsam/slam/tests/testSmartProjectionRigFactor.cpp
  gtsam_unstable/slam/README.md
  gtsam_unstable/slam/SmartProjectionPoseFactorRollingShutter.h
  gtsam_unstable/slam/tests/testSmartProjectionPoseFactorRollingShutter.cpp
Labels: feature

#904 Windows Fixes
  .github/workflows/build-windows.yml
  gtsam/nonlinear/NonlinearFactor.h
  gtsam/sfm/MFAS.h
  gtsam/slam/SmartFactorBase.h
  gtsam/slam/SmartProjectionPoseFactor.h
  gtsam_unstable/slam/LocalOrientedPlane3Factor.h
  gtsam_unstable/slam/ProjectionFactorPPPC.h
  gtsam_unstable/slam/ProjectionFactorRollingShutter.h
  gtsam_unstable/slam/SmartProjectionPoseFactorRollingShutter.h
  gtsam_unstable/slam/SmartStereoProjectionFactor.h
  gtsam_unstable/slam/SmartStereoProjectionFactorPP.h
  gtsam_unstable/slam/SmartStereoProjectionPoseFactor.h
Labels: quick-review, ci, windows

#965 Wrap Update
  matlab/gtsam_tests/testJacobianFactor.m
  matlab/gtsam_tests/testKalmanFilter.m
  matlab/gtsam_tests/testLocalizationExample.m
  matlab/gtsam_tests/testOdometryExample.m
  matlab/gtsam_tests/testPlanarSLAMExample.m
  matlab/gtsam_tests/testPose2SLAMExample.m
  matlab/gtsam_tests/testPose3SLAMExample.m
  matlab/gtsam_tests/testSFMExample.m
  matlab/gtsam_tests/testSerialization.m
  matlab/gtsam_tests/testStereoVOExample.m
  wrap/gtwrap/matlab_wrapper/wrapper.py
  wrap/tests/actual/.gitignore
  wrap/tests/expected/matlab/DefaultFuncInt.m
  wrap/tests/expected/matlab/DefaultFuncObj.m
  wrap/tests/expected/matlab/DefaultFuncString.m
  wrap/tests/expected/matlab/DefaultFuncVector.m
  wrap/tests/expected/matlab/DefaultFuncZero.m
  wrap/tests/expected/matlab/ForwardKinematics.m
  wrap/tests/expected/matlab/MyFactorPosePoint2.m
  wrap/tests/expected/matlab/TemplatedFunctionRot3.m
  wrap/tests/expected/matlab/class_wrapper.cpp
  wrap/tests/expected/matlab/functions_wrapper.cpp
  wrap/tests/expected/matlab/setPose.m
  wrap/tests/expected/python/functions_pybind.cpp
  wrap/tests/fixtures/functions.i
Labels: wrapper

#959 Add new insert_or_assign method to Values
  gtsam/nonlinear/Values-inl.h
  gtsam/nonlinear/Values.cpp
  gtsam/nonlinear/Values.h
  gtsam/nonlinear/nonlinear.i
  gtsam/nonlinear/tests/testValues.cpp
Labels: feature, quick-review

#970 Add wrapper fixes for Matlab memory leak
  gtsam/geometry/geometry.i
  gtsam/gtsam.i
  gtsam/linear/linear.i
  gtsam/navigation/navigation.i
  gtsam/nonlinear/nonlinear.i
  gtsam/slam/slam.i
  wrap/gtwrap/matlab_wrapper/templates.py
  wrap/gtwrap/matlab_wrapper/wrapper.py
  wrap/gtwrap/pybind_wrapper.py
  wrap/tests/expected/matlab/class_wrapper.cpp
  wrap/tests/expected/matlab/functions_wrapper.cpp
  wrap/tests/expected/matlab/geometry_wrapper.cpp
  wrap/tests/expected/matlab/inheritance_wrapper.cpp
  wrap/tests/expected/matlab/multiple_files_wrapper.cpp
  wrap/tests/expected/matlab/namespaces_wrapper.cpp
  wrap/tests/expected/matlab/special_cases_wrapper.cpp
  wrap/tests/expected/matlab/template_wrapper.cpp
  wrap/tests/fixtures/geometry.i
Labels: quick-review

#976 Spherical Camera Constructor Fix
  gtsam/geometry/SphericalCamera.h
  gtsam/slam/tests/smartFactorScenarios.h
  gtsam/slam/tests/testSmartProjectionRigFactor.cpp
  gtsam_unstable/slam/tests/testSmartProjectionPoseFactorRollingShutter.cpp
Labels: bugfix

#978 Use non-deprecated graphviz methods
  examples/FisheyeExample.cpp
  examples/Pose2SLAMExample_graphviz.cpp
Labels: quick-review, cleanup

#980 Wrapper Update
  python/gtsam_unstable/gtsam_unstable.tpl
  python/gtsam_unstable/specializations/gtsam_unstable.h
  wrap/cmake/PybindWrap.cmake
  wrap/gtwrap/pybind_wrapper.py
  wrap/scripts/pybind_wrap.py
Labels: python

#987 markdown for graphs
  gtsam/discrete/DecisionTreeFactor.h
  gtsam/discrete/DiscreteBayesNet.cpp
  gtsam/discrete/DiscreteBayesNet.h
  gtsam/discrete/DiscreteBayesTree.cpp
  gtsam/discrete/DiscreteBayesTree.h
  gtsam/discrete/DiscreteConditional.cpp
  gtsam/discrete/DiscreteConditional.h
  gtsam/discrete/DiscreteFactor.h
  gtsam/discrete/DiscreteFactorGraph.cpp
  gtsam/discrete/DiscreteFactorGraph.h
  gtsam/discrete/discrete.i
  gtsam/discrete/tests/testDiscreteBayesNet.cpp
  gtsam/discrete/tests/testDiscreteConditional.cpp
  gtsam/discrete/tests/testDiscreteFactorGraph.cpp
  gtsam_unstable/discrete/Constraint.h
  python/gtsam/notebooks/DiscreteSwitching.ipynb
Labels: feature, quick-review, wrapper

#988 _repr_markdown_ -> markdown
  gtsam/discrete/DecisionTreeFactor.cpp
  gtsam/discrete/DecisionTreeFactor.h
  gtsam/discrete/DiscreteConditional.cpp
  gtsam/discrete/DiscreteConditional.h
  gtsam/discrete/discrete.i
  gtsam/discrete/tests/testDecisionTreeFactor.cpp
  gtsam/discrete/tests/testDiscreteConditional.cpp
  python/gtsam/tests/test_DiscreteConditional.py
  wrap/gtwrap/pybind_wrapper.py
  wrap/tests/expected/matlab/ForwardKinematics.m
  wrap/tests/expected/matlab/MultipleTemplatesIntDouble.m
  wrap/tests/expected/matlab/MultipleTemplatesIntFloat.m
  wrap/tests/expected/matlab/MyFactorPosePoint2.m
  wrap/tests/expected/matlab/MyVector12.m
  wrap/tests/expected/matlab/MyVector3.m
  wrap/tests/expected/matlab/PrimitiveRefDouble.m
  wrap/tests/expected/matlab/Test.m
  wrap/tests/expected/matlab/class_wrapper.cpp
  wrap/tests/expected/python/class_pybind.cpp
  wrap/tests/fixtures/class.i
  wrap/tests/test_interface_parser.py
Labels: feature

#986 Create markdown representation
  gtsam/discrete/DecisionTreeFactor.cpp
  gtsam/discrete/DecisionTreeFactor.h
  gtsam/discrete/DiscreteBayesNet.cpp
  gtsam/discrete/DiscreteBayesNet.h
  gtsam/discrete/DiscreteBayesTree.cpp
  gtsam/discrete/DiscreteBayesTree.h
  gtsam/discrete/DiscreteConditional.cpp
  gtsam/discrete/DiscreteConditional.h
  gtsam/discrete/DiscreteFactor.h
  gtsam/discrete/DiscreteFactorGraph.cpp
  gtsam/discrete/DiscreteFactorGraph.h
  gtsam/discrete/DiscreteValues.h
  gtsam/discrete/discrete.i
  gtsam/discrete/tests/testDecisionTreeFactor.cpp
  gtsam/discrete/tests/testDiscreteBayesNet.cpp
  gtsam/discrete/tests/testDiscreteBayesTree.cpp
  gtsam/discrete/tests/testDiscreteConditional.cpp
  gtsam/discrete/tests/testDiscreteFactorGraph.cpp
  gtsam/discrete/tests/testDiscreteMarginals.cpp
  gtsam_unstable/discrete/Constraint.h
  python/gtsam/notebooks/DiscreteSwitching.ipynb
  python/gtsam/tests/test_DiscreteConditional.py
  wrap/gtwrap/pybind_wrapper.py
  wrap/tests/expected/matlab/ForwardKinematics.m
  wrap/tests/expected/matlab/MultipleTemplatesIntDouble.m
  wrap/tests/expected/matlab/MultipleTemplatesIntFloat.m
  wrap/tests/expected/matlab/MyFactorPosePoint2.m
  wrap/tests/expected/matlab/MyVector12.m
  wrap/tests/expected/matlab/MyVector3.m
  wrap/tests/expected/matlab/PrimitiveRefDouble.m
  wrap/tests/expected/matlab/Test.m
  wrap/tests/expected/matlab/class_wrapper.cpp
  wrap/tests/expected/python/class_pybind.cpp
  wrap/tests/fixtures/class.i
  wrap/tests/test_interface_parser.py
Labels: feature, quick-review, wrapper

#998 Moved empty to Factor base class.
  gtsam/discrete/DiscreteFactor.h
  gtsam/inference/Factor.h
  gtsam/linear/GaussianFactor.h
  gtsam/linear/HessianFactor.h
  gtsam/linear/JacobianFactor.h
  gtsam/slam/RegularImplicitSchurFactor.h
  gtsam/symbolic/SymbolicFactor.h
Labels: quick-review
