Repository borglab/gtsam, pull requests merged in 2021-03, with the labels that each got.

#691 Avoid target collision if gtsam used as submodule
  cmake/HandleUninstall.cmake
Labels: easy-fix

#711 Use wrap to perform Matlab wrapping
  CMakeLists.txt
  cmake/CMakeLists.txt
  cmake/GtsamMatlabWrap.cmake
  cmake/README.md
  cmake/example_project/CMakeLists.txt
  cmake/example_project/README.md
  cmake/example_project/SayGoodbye.cpp
  cmake/example_project/SayHello.cpp
  cmake/example_project/example.h
  cmake/example_project/example/PrintExamples.cpp
  cmake/example_project/example/PrintExamples.h
  cmake/example_project/tests/testExample.cpp
  gtsam/CMakeLists.txt
  gtsam/gtsam.i
  gtsam/linear/GaussianBayesNet.cpp
  gtsam/linear/GaussianBayesNet.h
  gtsam_unstable/CMakeLists.txt
  matlab/+gtsam/plotBayesNet.m
  matlab/+gtsam/plotBayesTree.m
  matlab/CMakeLists.txt
  matlab/gtsam_tests/testThinBayesTree.m
  matlab/gtsam_tests/testTriangulation.m
  matlab/gtsam_tests/thinBayesTree.m
  matlab/gtsam_tests/thinTreeBayesNet.m
  python/CMakeLists.txt
  python/gtsam/gtsam.tpl
  python/gtsam_unstable/gtsam_unstable.tpl
  wrap/CMakeLists.txt
  wrap/DOCS.md
  wrap/README.md
  wrap/cmake/MatlabWrap.cmake
  wrap/gtwrap/interface_parser.py
  wrap/gtwrap/matlab_wrapper.py
  wrap/gtwrap/pybind_wrapper.py
  wrap/gtwrap/template_instantiator.py
  wrap/pybind_wrapper.tpl.example
  wrap/scripts/pybind_wrap.py
  wrap/tests/expected-matlab/MultipleTemplatesIntDouble.m
  wrap/tests/expected-matlab/MultipleTemplatesIntFloat.m
  wrap/tests/expected-matlab/MyFactorPosePoint2.m
  wrap/tests/expected-matlab/aGlobalFunction.m
  wrap/tests/expected-matlab/geometry_wrapper.cpp
  wrap/tests/expected-matlab/load2D.m
  wrap/tests/expected-matlab/overloadedGlobalFunction.m
  wrap/tests/expected-python/geometry_pybind.cpp
  wrap/tests/geometry.h
  wrap/tests/pybind_wrapper.tpl
  wrap/tests/test_matlab_wrapper.py
  wrap/tests/test_pybind_wrapper.py
Labels: feature, matlab

#719 Fix the Similarity3 export declarations and wrapper
  gtsam/geometry/Similarity3.h
  gtsam/gtsam.i
Labels: bugfix, easy-fix, high-priority, quick-review

#720 Fix CI with separate boost install
  .github/scripts/boost.sh
  .github/scripts/python.sh
  .github/workflows/build-linux.yml
  .github/workflows/build-macos.yml
  .github/workflows/build-python.yml
  .github/workflows/build-special.yml
  .github/workflows/build-windows.yml
Labels: ci

#716 fix missing verbosityLMTranslator case
  gtsam/nonlinear/LevenbergMarquardtParams.cpp
Labels: bugfix, easy-fix

#726 Fix numpy deprecation warnings
  python/gtsam/examples/ImuFactorISAM2Example.py
  python/gtsam/examples/PlanarManipulatorExample.py
  python/gtsam/examples/Pose2SLAMExample.py
  python/gtsam/examples/Pose2SLAMExample_g2o.py
  python/gtsam/examples/Pose3SLAMExample_g2o.py
  python/gtsam/examples/PreintegrationExample.py
  python/gtsam/tests/test_SO4.py
  python/gtsam/tests/test_SOn.py
Labels: python
