Repository borglab/gtsam, pull requests merged in 2021-01, with the labels that each got.

#649 Add dataset directly to package
  .github/scripts/python.sh
  .github/workflows/build-python.yml
  python/CMakeLists.txt
  python/MANIFEST.in
  python/setup.py.in
Labels: cmake, python

#651 Remove Build Upload
  .github/workflows/build-linux.yml
  .github/workflows/build-macos.yml
  .github/workflows/build-windows.yml
Labels: ci, high-priority, quick-review

#617 Gnc
  gtsam/nonlinear/GaussNewtonOptimizer.h
  gtsam/nonlinear/GncOptimizer.h
  gtsam/nonlinear/GncParams.h
  gtsam/nonlinear/LevenbergMarquardtParams.h
  gtsam/nonlinear/NonlinearFactor.cpp
  gtsam/nonlinear/NonlinearFactor.h
  gtsam/nonlinear/NonlinearOptimizerParams.h
  tests/smallExample.h
  tests/testGncOptimizer.cpp
  tests/testNonlinearFactor.cpp
  tests/testNonlinearOptimizer.cpp
Labels: wip

#650 Adding serialization support to be used for GT-SFM
  gtsam/gtsam.i
  gtsam/slam/dataset.h
  gtsam/slam/tests/testSerializationDataset.cpp
Labels: enhancement, quick-review

#654 Updates to use the new version of wrap
  CMakeLists.txt
  cmake/GtsamMatlabWrap.cmake
  cmake/HandlePython.cmake
  python/CMakeLists.txt
  python/MANIFEST.in
  python/setup.py.in
  wrap/.gitignore
  wrap/CMakeLists.txt
  wrap/LICENSE
  wrap/README.md
  wrap/cmake/GtwrapUtils.cmake
  wrap/cmake/PybindWrap.cmake
  wrap/cmake/gtwrapConfig.cmake
  wrap/gtwrap/__init__.py
  wrap/gtwrap/interface_parser.py
  wrap/gtwrap/matlab_wrapper.py
  wrap/gtwrap/pybind_wrapper.py
  wrap/gtwrap/template_instantiator.py
  wrap/scripts/matlab_wrap.py
  wrap/scripts/pybind_wrap.py
  wrap/setup.py
  wrap/tests/interface_parser_test.py
  wrap/tests/test_matlab_wrapper.py
  wrap/tests/test_pybind_wrapper.py
Labels: matlab, python

#657 Fix warnings
  gtsam/3rdparty/metis/CMakeLists.txt
  gtsam/3rdparty/metis/libmetis/CMakeLists.txt
  gtsam/geometry/Pose3.cpp
  gtsam/geometry/SOn-inl.h
  gtsam/nonlinear/tests/testValues.cpp
  gtsam/sfm/ShonanAveraging.h
  gtsam/slam/GeneralSFMFactor.h
  gtsam/slam/dataset.h
  gtsam_unstable/examples/SmartRangeExample_plaza1.cpp
Labels: cmake, enhancement

#659 Adding default point color to `SfmTrack` to fix equality check
  gtsam/slam/dataset.h
Labels: bugfix, easy-fix, quick-review

#660 CMake Install Destination
  wrap/CMakeLists.txt
Labels: cmake

#652 Documentation for compiling on Windows
  INSTALL.md
Labels: docs

#547 Feature/robust shonan
  .cproject
  examples/ShonanAveragingCLI.cpp
  gtsam/sfm/BinaryMeasurement.h
  gtsam/sfm/ShonanAveraging.cpp
  gtsam/sfm/ShonanAveraging.h
  gtsam/sfm/tests/testBinaryMeasurement.cpp
  gtsam/sfm/tests/testShonanAveraging.cpp
  gtsam/slam/FrobeniusFactor.cpp
  gtsam/slam/FrobeniusFactor.h
Labels: feature

#664 Update wrapper
  wrap/CMakeLists.txt
  wrap/cmake/GtwrapUtils.cmake
Labels: cmake, python, quick-review

#665 Update wrapper
  wrap/cmake/GtwrapUtils.cmake
  wrap/setup.py
Labels: python, quick-review

#671 FunctorizedFactor2
  gtsam/nonlinear/FunctorizedFactor.h
  gtsam/nonlinear/tests/testFunctorizedFactor.cpp
Labels: enhancement, feature

#675 changing robust noise model to Gaussian
  gtsam/sfm/ShonanAveraging.cpp
Labels: bugfix, easy-fix, quick-review

#679 Miscellaneous fixes
  gtsam/gtsam.i
  gtsam_unstable/slam/SmartStereoProjectionPoseFactor.h
Labels: enhancement

#678 Better printing
  gtsam/base/Matrix.cpp
  gtsam/base/Testable.h
  gtsam/geometry/Pose2.cpp
  gtsam/geometry/Pose2.h
Labels: bugfix, feature

#533 Added accelerated power method to compute eigenpair fast
  gtsam/linear/AcceleratedPowerMethod.h
  gtsam/linear/PowerMethod.h
  gtsam/linear/tests/powerMethodExample.h
  gtsam/linear/tests/testAcceleratedPowerMethod.cpp
  gtsam/linear/tests/testPowerMethod.cpp
  gtsam/sfm/ShonanAveraging.cpp
  gtsam/sfm/ShonanAveraging.h
  gtsam/sfm/tests/testShonanAveraging.cpp
Labels: feature

#685 Fix Pose2 print
  gtsam/base/Testable.h
  gtsam/base/TestableAssertions.h
  gtsam/geometry/Pose2.cpp
  gtsam/geometry/tests/testPose2.cpp
  gtsam/navigation/CombinedImuFactor.cpp
  gtsam/navigation/ImuFactor.cpp
  gtsam/navigation/PreintegratedRotation.cpp
  gtsam/navigation/PreintegrationBase.cpp
  gtsam/nonlinear/Values.cpp
  gtsam/sfm/ShonanAveraging.h
Labels: bugfix

#681 Known Issues Section
  INSTALL.md
Labels: bugfix, docs

#683 Update CMake Variables and TBB build type
  cmake/FindTBB.cmake
  cmake/GtsamBuildTypes.cmake
Labels: bugfix
