Repository borglab/gtsam, pull requests merged in 2021-06, with the labels that each got.

#779 Added destructor for `CameraSet` to remove warning
  gtsam/geometry/CameraSet.h
Labels: easy-fix

#775 Fix initial guess for Cal3Bundler `calibrate`
  gtsam/geometry/Cal3Bundler.cpp
  gtsam/geometry/tests/testCal3Bundler.cpp
Labels: bugfix

#785 Fix bug in LinearContainerFactor and warnings about Point3
  gtsam/nonlinear/LinearContainerFactor.cpp
  gtsam/nonlinear/tests/testLinearContainerFactor.cpp
Labels: bugfix, easy-fix, quick-review

#771 Correct ImuFactorExamples frame description
  examples/CombinedImuFactorsExample.cpp
  examples/ImuFactorsExample.cpp
Labels: docs

#774 Fix docstrings for NonlinearEquality
  gtsam/nonlinear/NonlinearEquality.h
Labels: quick-review

#793 add expressions for cross() and dot()
  gtsam/slam/expressions.h
  tests/testExpressionFactor.cpp
Labels: enhancement, quick-review

#794 Remove separate function for double in wrapper
  gtsam/gtsam.i
  python/CMakeLists.txt
  python/README.md
Labels: matlab, python

#799 Wrap Update
  wrap/.github/workflows/linux-ci.yml
  wrap/.github/workflows/macos-ci.yml
  wrap/DOCS.md
  wrap/gtwrap/interface_parser/classes.py
  wrap/gtwrap/interface_parser/declaration.py
  wrap/gtwrap/interface_parser/function.py
  wrap/gtwrap/interface_parser/namespace.py
  wrap/gtwrap/interface_parser/tokens.py
  wrap/gtwrap/interface_parser/variable.py
  wrap/gtwrap/matlab_wrapper.py
  wrap/gtwrap/pybind_wrapper.py
  wrap/gtwrap/template_instantiator.py
  wrap/scripts/matlab_wrap.py
  wrap/scripts/pybind_wrap.py
  wrap/setup.py
  wrap/tests/expected/matlab/MultipleTemplatesIntDouble.m
  wrap/tests/expected/matlab/MultipleTemplatesIntFloat.m
  wrap/tests/expected/matlab/MyFactorPosePoint2.m
  wrap/tests/expected/matlab/MyVector12.m
  wrap/tests/expected/matlab/MyVector3.m
  wrap/tests/expected/matlab/PrimitiveRefDouble.m
  wrap/tests/expected/matlab/TemplatedFunctionRot3.m
  wrap/tests/expected/matlab/Test.m
  wrap/tests/expected/matlab/class_wrapper.cpp
  wrap/tests/expected/matlab/functions_wrapper.cpp
  wrap/tests/expected/matlab/geometry_wrapper.cpp
  wrap/tests/expected/matlab/inheritance_wrapper.cpp
  wrap/tests/expected/matlab/namespaces_wrapper.cpp
  wrap/tests/expected/matlab/special_cases_wrapper.cpp
  wrap/tests/expected/python/class_pybind.cpp
  wrap/tests/expected/python/functions_pybind.cpp
  wrap/tests/expected/python/namespaces_pybind.cpp
  wrap/tests/fixtures/class.i
  wrap/tests/fixtures/functions.i
  wrap/tests/fixtures/namespaces.i
  wrap/tests/test_docs.py
  wrap/tests/test_interface_parser.py
  wrap/tests/test_matlab_wrapper.py
  wrap/tests/test_pybind_wrapper.py
Labels: wrapper

#792 Switching to squared sampson point-line error
  gtsam/geometry/EssentialMatrix.cpp
  gtsam/geometry/EssentialMatrix.h
  gtsam/geometry/tests/testEssentialMatrix.cpp
  gtsam/slam/tests/testEssentialMatrixFactor.cpp
Labels: wip

#802 Update the pgp servers to get the LLVM GPG key
  .github/workflows/build-linux.yml
  .github/workflows/build-python.yml
  .github/workflows/build-special.yml
Labels: bugfix
