Repository borglab/gtsam, pull requests merged in 2022-02, with the labels that each got.

#1077 Wrapped more things
  gtsam/discrete/discrete.i
  gtsam/discrete/tests/testDiscreteBayesTree.cpp
  gtsam/inference/BayesTree-inst.h
  gtsam/inference/inference.i
  gtsam/linear/linear.i
  gtsam/nonlinear/nonlinear.i
  gtsam/sam/sam.i
  gtsam/slam/dataset.cpp
  gtsam/slam/dataset.h
  gtsam/slam/slam.i
  python/gtsam/tests/test_GaussianBayesNet.py
  python/gtsam/tests/test_GraphvizFormatting.py
Labels: quick-review

#1082 Cleaned up loading SfmData
  examples/SFMExampleExpressions_bal.cpp
  examples/SFMExample_bal.cpp
  examples/SFMExample_bal_COLAMD_METIS.cpp
  gtsam/navigation/ImuBias.cpp
  gtsam/sfm/SfmData.cpp
  gtsam/sfm/SfmData.h
  gtsam/sfm/SfmTrack.h
  gtsam/sfm/sfm.i
  gtsam/sfm/tests/testSfmData.cpp
  gtsam/slam/tests/testEssentialMatrixFactor.cpp
  gtsam/slam/tests/testSerializationDataset.cpp
  python/gtsam/examples/SFMExample_bal.py
  python/gtsam/examples/SimpleRotation.py
  python/gtsam/examples/VisualISAMExample.py
  python/gtsam/tests/test_SfmData.py
  python/gtsam/utils/visual_data_generator.py
  tests/testGeneralSFMFactorB.cpp
  tests/testTranslationRecovery.cpp
  timing/timeSFMBAL.h
  timing/timeSFMBALautodiff.cpp
Labels: quick-review, high-priority

#1084 Wrapper Update
  wrap/gtwrap/matlab_wrapper/mixins.py
  wrap/gtwrap/matlab_wrapper/wrapper.py
  wrap/matlab.h
  wrap/tests/expected/matlab/ForwardKinematicsFactor.m
  wrap/tests/expected/matlab/functions_wrapper.cpp
  wrap/tests/expected/matlab/geometry_wrapper.cpp
  wrap/tests/expected/matlab/inheritance_wrapper.cpp
  wrap/tests/expected/python/inheritance_pybind.cpp
  wrap/tests/fixtures/inheritance.i
Labels: quick-review

#1089 Fix DotWriter wrapping
  gtsam/discrete/tests/testDiscreteBayesNet.cpp
  python/gtsam/preamble/inference.h
  python/gtsam/tests/test_DiscreteBayesNet.py
Labels: high-priority

#1091 Improvements in linear
  gtsam/linear/GaussianBayesNet.cpp
  gtsam/linear/GaussianBayesNet.h
  gtsam/linear/GaussianConditional.cpp
  gtsam/linear/GaussianConditional.h
  gtsam/linear/GaussianDensity.cpp
  gtsam/linear/GaussianDensity.h
  gtsam/linear/Sampler.cpp
  gtsam/linear/Sampler.h
  gtsam/linear/linear.i
  gtsam/linear/tests/testGaussianBayesNet.cpp
  gtsam/linear/tests/testGaussianConditional.cpp
  gtsam/linear/tests/testGaussianDensity.cpp
  tests/testGaussianBayesTreeB.cpp
Labels: quick-review

#1095 New functionality in linear
  gtsam/base/FastSet.h
  gtsam/base/serialization.h
  gtsam/discrete/DiscreteConditional.cpp
  gtsam/discrete/DiscreteConditional.h
  gtsam/linear/GaussianConditional.cpp
  gtsam/linear/GaussianConditional.h
  gtsam/linear/VectorValues.cpp
  gtsam/linear/VectorValues.h
  gtsam/linear/linear.i
  gtsam/linear/tests/testGaussianConditional.cpp
  gtsam/linear/tests/testVectorValues.cpp
Labels: quick-review

#1115 CMake Warning Fixes
  CMakeLists.txt
  tests/CMakeLists.txt
Labels: cmake, quick-review

#1109 Windows Tests
  .github/workflows/build-windows.yml
  DEVELOP.md
  Using-GTSAM-EXPORT.md
  cmake/GtsamBuildTypes.cmake
  gtsam/basis/Basis.h
  gtsam/basis/BasisFactors.h
  gtsam/basis/Chebyshev.h
  gtsam/basis/Fourier.h
  gtsam/basis/basis.i
  gtsam/discrete/AlgebraicDecisionTree.cpp
  gtsam/discrete/AlgebraicDecisionTree.h
  gtsam/discrete/DiscreteLookupDAG.h
  gtsam/discrete/DiscreteMarginals.h
  gtsam/discrete/DiscreteValues.h
  gtsam/discrete/tests/testAlgebraicDecisionTree.cpp
  gtsam/geometry/Line3.cpp
  gtsam/geometry/Line3.h
  gtsam/geometry/SOn.cpp
  gtsam/geometry/SOn.h
  gtsam/geometry/Unit3.h
  gtsam/inference/tests/testOrdering.cpp
  gtsam/navigation/CombinedImuFactor.cpp
  gtsam/navigation/CombinedImuFactor.h
  gtsam/navigation/tests/testSerializationNavigation.cpp
  gtsam/nonlinear/FunctorizedFactor.h
  gtsam/nonlinear/LinearContainerFactor.h
  gtsam/slam/FrobeniusFactor.h
  gtsam/slam/OrientedPlane3Factor.h
  gtsam/slam/SmartProjectionPoseFactor.h
  gtsam/slam/dataset.cpp
  gtsam/symbolic/tests/testSymbolicBayesTree.cpp
Labels: bugfix, ci
