Repository borglab/gtsam, pull requests merged in 2022-01, with the labels that each got.

#1022 html renderers in discrete
  examples/UGM_small.cpp
  gtsam/discrete/Assignment.h
  gtsam/discrete/DecisionTreeFactor.cpp
  gtsam/discrete/DecisionTreeFactor.h
  gtsam/discrete/DiscreteBayesNet.cpp
  gtsam/discrete/DiscreteBayesNet.h
  gtsam/discrete/DiscreteBayesTree.cpp
  gtsam/discrete/DiscreteBayesTree.h
  gtsam/discrete/DiscreteConditional.cpp
  gtsam/discrete/DiscreteConditional.h
  gtsam/discrete/DiscreteFactor.cpp
  gtsam/discrete/DiscreteFactor.h
  gtsam/discrete/DiscreteFactorGraph.cpp
  gtsam/discrete/DiscreteFactorGraph.h
  gtsam/discrete/DiscreteValues.cpp
  gtsam/discrete/DiscreteValues.h
  gtsam/discrete/discrete.i
  gtsam/discrete/tests/testDecisionTreeFactor.cpp
  gtsam/discrete/tests/testDiscreteBayesNet.cpp
  gtsam/discrete/tests/testDiscreteBayesTree.cpp
  gtsam/discrete/tests/testDiscreteConditional.cpp
  gtsam/discrete/tests/testDiscreteMarginals.cpp
  gtsam/discrete/tests/testDiscreteValues.cpp
  gtsam_unstable/discrete/CSP.cpp
  gtsam_unstable/discrete/Constraint.h
  gtsam_unstable/discrete/Scheduler.h
  gtsam_unstable/discrete/tests/testLoopyBelief.cpp
  python/gtsam/tests/test_DiscreteConditional.py
  python/gtsam/tests/test_DiscretePrior.py
Labels: high-priority

#1028 Wrap double for between factor
  gtsam/slam/slam.i
  python/gtsam/tests/test_BetweenFactor.py
Labels: quick-review

#1030 FG print(): fix empty lines on nullptr; avoid endl
  gtsam/nonlinear/NonlinearFactorGraph.cpp
Labels: bugfix, quick-review, low-priority

#1034 Fix probPrime
  gtsam/linear/GaussianFactorGraph.h
  gtsam/linear/tests/testGaussianFactorGraph.cpp
  gtsam/nonlinear/NonlinearFactorGraph.cpp
  gtsam/nonlinear/NonlinearFactorGraph.h
  tests/testNonlinearFactorGraph.cpp
Labels: bugfix

#1037 Better DiscreteConditional
  gtsam/discrete/DecisionTreeFactor.h
  gtsam/discrete/DiscreteConditional.cpp
  gtsam/discrete/DiscreteConditional.h
  gtsam/discrete/DiscretePrior.h
  gtsam/discrete/discrete.i
  gtsam/discrete/tests/testDecisionTreeFactor.cpp
  gtsam/discrete/tests/testDiscreteConditional.cpp
  gtsam/discrete/tests/testDiscretePrior.cpp
  gtsam/slam/slam.i
  python/gtsam/tests/test_DecisionTreeFactor.py
  python/gtsam/tests/test_DiscreteConditional.py
  python/gtsam/tests/test_DiscretePrior.py
Labels: quick-review, high-priority

#1050 Fix DiscreteFactorGraph::optimize to return MPE
  examples/DiscreteBayesNetExample.cpp
  examples/DiscreteBayesNet_FG.cpp
  examples/HMMExample.cpp
  examples/UGM_chain.cpp
  examples/UGM_small.cpp
  gtsam/discrete/DecisionTreeFactor.cpp
  gtsam/discrete/DecisionTreeFactor.h
  gtsam/discrete/DiscreteBayesNet.cpp
  gtsam/discrete/DiscreteBayesNet.h
  gtsam/discrete/DiscreteConditional.cpp
  gtsam/discrete/DiscreteConditional.h
  gtsam/discrete/DiscreteDistribution.h
  gtsam/discrete/DiscreteFactorGraph.cpp
  gtsam/discrete/DiscreteFactorGraph.h
  gtsam/discrete/DiscreteKey.cpp
  gtsam/discrete/DiscreteLookupDAG.cpp
  gtsam/discrete/DiscreteLookupDAG.h
  gtsam/discrete/discrete.i
  gtsam/discrete/tests/testDiscreteBayesNet.cpp
  gtsam/discrete/tests/testDiscreteDistribution.cpp
  gtsam/discrete/tests/testDiscreteFactorGraph.cpp
  gtsam/discrete/tests/testDiscreteLookupDAG.cpp
  gtsam/inference/Conditional.h
  gtsam_unstable/discrete/CSP.cpp
  gtsam_unstable/discrete/CSP.h
  gtsam_unstable/discrete/Scheduler.cpp
  gtsam_unstable/discrete/Scheduler.h
  gtsam_unstable/discrete/examples/schedulingExample.cpp
  gtsam_unstable/discrete/examples/schedulingQuals12.cpp
  gtsam_unstable/discrete/examples/schedulingQuals13.cpp
  gtsam_unstable/discrete/tests/testCSP.cpp
  gtsam_unstable/discrete/tests/testScheduler.cpp
  gtsam_unstable/discrete/tests/testSudoku.cpp
  python/gtsam/tests/test_DiscreteBayesNet.py
  python/gtsam/tests/test_DiscreteDistribution.py
Labels: bugfix, high-priority

#1055 Changes in gtsam to support hybrid branches
  gtsam/base/utilities.cpp
  gtsam/base/utilities.h
  gtsam/discrete/AlgebraicDecisionTree.h
  gtsam/discrete/DecisionTree-inl.h
  gtsam/discrete/DecisionTree.h
  gtsam/discrete/DecisionTreeFactor.cpp
  gtsam/discrete/DecisionTreeFactor.h
  gtsam/discrete/DiscreteFactor.cpp
  gtsam/discrete/DiscreteFactor.h
  gtsam/discrete/DiscreteFactorGraph.cpp
  gtsam/discrete/DiscreteFactorGraph.h
  gtsam/discrete/DiscreteKey.h
  gtsam/discrete/DiscreteMarginals.h
  gtsam/discrete/tests/testDecisionTree.cpp
  gtsam/inference/Factor.h
  gtsam/inference/FactorGraph.h
  gtsam/inference/MetisIndex-inl.h
  gtsam/inference/MetisIndex.h
  gtsam/linear/GaussianFactorGraph.h
Labels: quick-review

#1066 Added sumProduct as a convenient alias
  gtsam/discrete/DiscreteFactorGraph.cpp
  gtsam/discrete/DiscreteFactorGraph.h
  gtsam/discrete/discrete.i
  gtsam/discrete/tests/testDiscreteFactorGraph.cpp
  gtsam/nonlinear/nonlinear.i
  python/gtsam/tests/test_DiscreteFactorGraph.py
Labels: quick-review, high-priority

#1068 Added inference module
  gtsam/discrete/discrete.i
  gtsam/inference/inference.i
  gtsam/nonlinear/nonlinear.i
  gtsam/symbolic/symbolic.i
  python/CMakeLists.txt
  python/gtsam/preamble/inference.h
  python/gtsam/specializations/inference.h
Labels: quick-review, high-priority

#1070 Added support for positioning in BayesNet plotting
  gtsam/discrete/DiscreteBayesNet.h
  gtsam/discrete/discrete.i
  gtsam/discrete/tests/testDiscreteBayesNet.cpp
  gtsam/inference/BayesNet-inst.h
  gtsam/inference/BayesNet.h
  gtsam/inference/DotWriter.cpp
  gtsam/inference/DotWriter.h
  gtsam/inference/FactorGraph-inst.h
  gtsam/inference/inference.i
  gtsam/linear/GaussianBayesNet.cpp
  gtsam/linear/GaussianBayesNet.h
  gtsam/linear/linear.i
  gtsam/linear/tests/testGaussianBayesNet.cpp
  gtsam/nonlinear/GraphvizFormatting.cpp
  gtsam/nonlinear/GraphvizFormatting.h
  gtsam/nonlinear/NonlinearFactorGraph.cpp
  gtsam/nonlinear/NonlinearFactorGraph.h
  gtsam/nonlinear/nonlinear.i
  gtsam/symbolic/SymbolicBayesNet.cpp
  gtsam/symbolic/SymbolicBayesNet.h
  gtsam/symbolic/symbolic.i
  gtsam/symbolic/tests/testSymbolicBayesNet.cpp
  python/gtsam/tests/test_GraphvizFormatting.py
Labels: high-priority
